Separating the Gao Paper (Esophageal Cancer) Pre-treatment and Post-treatment Data

In [1]:
# Import the packages we may need
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [2]:
# Read in the file

Metadata_df=pd.read_excel("Gao_JImmunoTher_Supp_Edited.xlsx", "1. Meta data") # This is the esophageal cancer data set
# Data set source: https://pmc.ncbi.nlm.nih.gov/articles/PMC10836376/

In [3]:
# Visualize the dataframe
Metadata_df.head()

   sample_id collected matched         treatment
0  R21043026   pre-trm       no  ICI monotherapy
1  R21043028   pre-trm      yes  ICI monotherapy
2  R21043029  post-trm      yes  ICI monotherapy
3  R21043030   pre-trm      yes  ICI monotherapy
4  R21043031  post-trm      yes  ICI monotherapy

In [4]:
# Separate pretreatment from posttreatment meta data
pretreatmentlist_df=Metadata_df[(Metadata_df['collected'] == 'pre-trm')]
posttreatmentlist_df=Metadata_df[(Metadata_df['collected'] == 'post-trm')]

In [5]:
# Verify the number of samples that are in the pre-treatment group
len(pretreatmentlist_df)

91

In [6]:
# Get IDs of pre-treatment and post-treatment samples
pretreatmentIDs=pretreatmentlist_df['sample_id']
posttreatmentIDs=posttreatmentlist_df['sample_id']

In [7]:
# Verify again the number of samples that are in the pre-treatment group
len(pretreatmentIDs)

91

In [8]:
# Verify the number of samples that are in the post-treatment group
len(posttreatmentIDs)

67

In [9]:
# Read in the NPX data
Gao_NPX_df=pd.read_excel("Gao_JImmunoTher_Supp_Edited.xlsx", "2. Quantification, NPX") 
Gao_NPX_df.head(15)

,sample_id,P10145,Q07011,Q02763,P80098,P29965,P01583,Q9BZW8,P01133,Q15389,...,P35225,P78556,P01375,Q13241,P10144,Q01151,"P29459,P29460",P09603,Unnamed: 93,Unnamed: 94
0,R21043026,4.89898,6.01419,6.73672,1.35202,5.95495,-2.79663,5.65495,8.67672,7.897,...,0.41607,6.12544,2.12797,5.33351,5.92401,2.47693,5.64796,9.40197,plate1_1362562541.csv,Pass
1,R21043028,6.10887,5.49825,7.37053,1.29614,7.98518,-2.6627,6.26213,10.21614,9.16064,...,-0.00857,9.15514,2.46813,5.66605,5.49523,2.39335,6.81496,9.82524,plate2_1362562385.csv,Pass
2,R21043029,5.70996,6.09159,7.34064,1.21325,6.27686,-2.78854,5.80786,8.94415,8.19971,...,0.5048,9.02045,3.11719,5.73455,5.58544,2.56636,7.53077,9.85865,plate2_1362562385.csv,Pass
3,R21043030,4.44095,5.60867,7.59944,0.94615,4.94,-2.74069,5.82213,7.39997,6.78645,...,-0.12533,6.16322,2.61357,5.52813,3.98589,2.71992,6.83475,9.16964,plate1_1362562541.csv,Pass
4,R21043031,4.58833,5.55981,7.26801,0.91438,6.15534,-2.94187,5.89687,8.57039,7.96583,...,0.56337,6.17149,2.45316,5.46034,4.01586,2.71827,7.10535,8.92031,plate1_1362562541.csv,Pass
5,R21043032,7.6427,5.4599,7.20598,2.49907,8.19881,-2.09092,5.98716,10.72494,9.73018,...,0.72216,9.18583,2.71404,5.86032,5.50904,1.80735,6.23084,9.63688,plate1_1362562541.csv,Pass
6,R21043033,8.012,5.30809,7.60848,2.86987,8.7446,-2.34668,6.48364,10.62841,9.39108,...,0.64641,9.16829,2.46513,6.20696,5.74939,1.94023,6.00596,9.69115,plate1_1362562541.csv,Pass
7,R21043034,7.26992,6.62226,7.10424,2.59908,8.9658,-0.06198,6.94189,11.08722,9.84664,...,0.18909,8.48542,3.57668,6.36265,6.26009,2.79629,7.62235,9.78305,plate2_1362562385.csv,Pass
8,R21043035,7.8652,6.75182,7.23996,2.96679,8.87998,2.05571,7.0852,11.33516,10.12143,...,1.07157,10.88388,3.40709,6.47545,5.58264,2.57233,6.77072,9.79084,plate1_1362562541.csv,Pass
9,R21043036,5.35178,5.86844,6.61774,1.75922,7.56376,-2.3027,5.60631,9.47385,8.19895,...,0.90151,7.61078,2.43857,4.89465,4.93348,2.57071,6.03402,9.37822,plate2_1362562385.csv,Pass
10,R21043037,4.69217,6.29241,6.94207,1.36992,5.64655,-2.62572,5.45393,7.37005,6.94131,...,0.55952,6.94842,2.58028,5.16934,5.28083,2.70858,6.33247,9.40829,plate2_1362562385.csv,Pass
11,R21043038,6.14246,6.00516,6.94127,1.78955,2.79903,-2.18047,5.08345,5.25143,5.58798,...,0.14716,7.464,2.65736,5.39196,3.63704,2.23685,6.24256,9.36871,plate2_1362562385.csv,Pass
12,R21043039,6.95214,6.93276,7.28219,2.59579,7.94422,-1.45714,6.37259,10.26842,9.20391,...,0.41961,8.27209,3.36594,5.76304,4.93348,2.69971,7.41918,9.83031,plate1_1362562541.csv,Pass
13,R21043040,5.59958,4.92705,6.78342,1.44002,6.91034,-1.34021,5.57711,9.07897,8.46699,...,0.96647,6.35105,2.37421,5.09528,4.53309,2.19132,6.16382,9.34945,plate2_1362562385.csv,Pass
14,R21043041,6.27533,5.5587,7.17565,1.42378,7.12796,-0.798,5.61554,9.26114,8.58865,...,0.33244,7.02825,2.35325,5.4316,5.33178,2.40177,6.40538,9.44216,plate2_1362562385.csv,Pass

In [10]:
# Separate pretreatment from posttreatment NPX dataframes
Gao_NPX_pretreatment_df= Gao_NPX_df[(Gao_NPX_df['sample_id'].isin(pretreatmentIDs))]
Gao_NPX_posttreatment_df= Gao_NPX_df[(Gao_NPX_df['sample_id'].isin(posttreatmentIDs))]

In [11]:
# Visualize the pre-treatment NPX dataframe
Gao_NPX_pretreatment_df

,sample_id,P10145,Q07011,Q02763,P80098,P29965,P01583,Q9BZW8,P01133,Q15389,...,P35225,P78556,P01375,Q13241,P10144,Q01151,"P29459,P29460",P09603,Unnamed: 93,Unnamed: 94
0,R21043026,4.89898,6.01419,6.73672,1.35202,5.95495,-2.79663,5.65495,8.67672,7.897,...,0.41607,6.12544,2.12797,5.33351,5.92401,2.47693,5.64796,9.40197,plate1_1362562541.csv,Pass
1,R21043028,6.10887,5.49825,7.37053,1.29614,7.98518,-2.6627,6.26213,10.21614,9.16064,...,-0.00857,9.15514,2.46813,5.66605,5.49523,2.39335,6.81496,9.82524,plate2_1362562385.csv,Pass
3,R21043030,4.44095,5.60867,7.59944,0.94615,4.94,-2.74069,5.82213,7.39997,6.78645,...,-0.12533,6.16322,2.61357,5.52813,3.98589,2.71992,6.83475,9.16964,plate1_1362562541.csv,Pass
5,R21043032,7.6427,5.4599,7.20598,2.49907,8.19881,-2.09092,5.98716,10.72494,9.73018,...,0.72216,9.18583,2.71404,5.86032,5.50904,1.80735,6.23084,9.63688,plate1_1362562541.csv,Pass
7,R21043034,7.26992,6.62226,7.10424,2.59908,8.9658,-0.06198,6.94189,11.08722,9.84664,...,0.18909,8.48542,3.57668,6.36265,6.26009,2.79629,7.62235,9.78305,plate2_1362562385.csv,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,R21043189,5.50472,5.58135,6.97665,3.77736,4.77267,-2.47428,5.15132,7.7067,7.55051,...,0.33824,6.31966,2.4555,4.75981,4.03573,2.2342,6.15278,9.34475,plate1_1362562541.csv,Pass
154,R21043190,5.91264,5.97964,6.9583,1.94123,7.40513,-2.37196,5.67269,9.01016,8.63523,...,0.96682,7.03317,2.6664,5.56452,6.36672,2.18414,7.04233,9.35815,plate2_1362562385.csv,Pass
155,R21043191,5.72444,5.68711,7.31255,1.37689,6.99498,-2.95881,5.56302,8.58966,9.37883,...,0.68809,5.38443,1.97106,4.27538,5.2723,2.16836,6.60739,9.09003,plate2_1362562385.csv,Pass
156,R21043192,6.32457,5.62306,7.3167,1.41937,6.99395,-2.24831,5.70772,8.98579,8.37097,...,0.25039,7.20985,2.86651,4.59005,4.4014,2.90811,6.9751,9.61646,plate2_1362562385.csv,Pass
157,R21043193,6.74214,6.3424,7.64777,1.47425,7.64532,-2.31526,6.3272,9.62815,8.91116,...,1.57588,7.05905,2.91979,5.78497,4.99235,2.8411,6.41986,9.6847,plate1_1362562541.csv,Pass

In [12]:
# Export the pretreatment and posttreatment dataframes
Gao_NPX_pretreatment_df.to_csv("Gao_pretreatment.csv", index=False)
Gao_NPX_posttreatment_df.to_csv("Gao_posttreatment.csv", index=False)