In [1]:
#convert txt file to csv file. Defined as "df1", since it redefines as "df" to ease of use after columns are seperated
#initially, data frame defined as 'df1',  after separating columns for ease of use it redefined as 'df' for all later use
#pancancer.txt dataset downloaded from "https://pmc.ncbi.nlm.nih.gov/articles/PMC10354027/#notes4" 

import pandas as pd
df1 = pd.read_fwf('pancancer.txt')
df1.to_csv('pancancer_old.csv')
df1

        "Sample_ID" "Cancer" "Assay" "OlinkID" "UniProt" "Panel" "NPX"
0        "AML_1" "AML" "AARSD1" "OID21311" "Q9BTE6" "On...
1        "AML_2" "AML" "AARSD1" "OID21311" "Q9BTE6" "On...
2        "AML_3" "AML" "AARSD1" "OID21311" "Q9BTE6" "On...
3        "AML_4" "AML" "AARSD1" "OID21311" "Q9BTE6" "On...
4        "AML_5" "AML" "AARSD1" "OID21311" "Q9BTE6" "On...
...                                                    ...
2082004  "PRC_157" "PRC" "ZBTB17" "OID20082" "Q13105" "...
2082005  "PRC_159" "PRC" "ZBTB17" "OID20082" "Q13105" "...
2082006  "PRC_160" "PRC" "ZBTB17" "OID20082" "Q13105" "...
2082007  "PRC_161" "PRC" "ZBTB17" "OID20082" "Q13105" "...
2082008  "PRC_163" "PRC" "ZBTB17" "OID20082" "Q13105" "...

[2082009 rows x 1 columns]

In [2]:
# since both txt and csv files behave they have only one combined column, it has to be splitted different colums.

df = df1['"Sample_ID" "Cancer" "Assay" "OlinkID" "UniProt" "Panel" "NPX"'].str.split(' ', expand= True)
df

,0,1,2,3,4,5,6
0,"""AML_1""","""AML""","""AARSD1""","""OID21311""","""Q9BTE6""","""Oncology""",5.01745
1,"""AML_2""","""AML""","""AARSD1""","""OID21311""","""Q9BTE6""","""Oncology""",2.8679
2,"""AML_3""","""AML""","""AARSD1""","""OID21311""","""Q9BTE6""","""Oncology""",4.58825
3,"""AML_4""","""AML""","""AARSD1""","""OID21311""","""Q9BTE6""","""Oncology""",1.97255
4,"""AML_5""","""AML""","""AARSD1""","""OID21311""","""Q9BTE6""","""Oncology""",3.45995
...,...,...,...,...,...,...,...
2082004,"""PRC_157""","""PRC""","""ZBTB17""","""OID20082""","""Q13105""","""Cardiometabolic""",0.99695
2082005,"""PRC_159""","""PRC""","""ZBTB17""","""OID20082""","""Q13105""","""Cardiometabolic""",1.1206
2082006,"""PRC_160""","""PRC""","""ZBTB17""","""OID20082""","""Q13105""","""Cardiometabolic""",1.61685
2082007,"""PRC_161""","""PRC""","""ZBTB17""","""OID20082""","""Q13105""","""Cardiometabolic""",0.91665
2082008,"""PRC_163""","""PRC""","""ZBTB17""","""OID20082""","""Q13105""","""Cardiometabolic""",1.3003

In [3]:
#after splitting columns as desired, name them as stated in the file

df.columns=['Sample_ID', 'Cancer', 'Assay', 'OlinkID', 'UniProt', 'Panel', 'NPX']

df

,Sample_ID,Cancer,Assay,OlinkID,UniProt,Panel,NPX
0,"""AML_1""","""AML""","""AARSD1""","""OID21311""","""Q9BTE6""","""Oncology""",5.01745
1,"""AML_2""","""AML""","""AARSD1""","""OID21311""","""Q9BTE6""","""Oncology""",2.8679
2,"""AML_3""","""AML""","""AARSD1""","""OID21311""","""Q9BTE6""","""Oncology""",4.58825
3,"""AML_4""","""AML""","""AARSD1""","""OID21311""","""Q9BTE6""","""Oncology""",1.97255
4,"""AML_5""","""AML""","""AARSD1""","""OID21311""","""Q9BTE6""","""Oncology""",3.45995
...,...,...,...,...,...,...,...
2082004,"""PRC_157""","""PRC""","""ZBTB17""","""OID20082""","""Q13105""","""Cardiometabolic""",0.99695
2082005,"""PRC_159""","""PRC""","""ZBTB17""","""OID20082""","""Q13105""","""Cardiometabolic""",1.1206
2082006,"""PRC_160""","""PRC""","""ZBTB17""","""OID20082""","""Q13105""","""Cardiometabolic""",1.61685
2082007,"""PRC_161""","""PRC""","""ZBTB17""","""OID20082""","""Q13105""","""Cardiometabolic""",0.91665
2082008,"""PRC_163""","""PRC""","""ZBTB17""","""OID20082""","""Q13105""","""Cardiometabolic""",1.3003

In [4]:
# Create a new CSV file from the split DataFrame
output_csv_file = 'pancancer.csv'

# Save the split DataFrame to a CSV file
df.to_csv(output_csv_file, index=False)

print(f"Successfully saved the split DataFrame to '{output_csv_file}'.")
df

Successfully saved the split DataFrame to 'pancancer.csv'.

,Sample_ID,Cancer,Assay,OlinkID,UniProt,Panel,NPX
0,"""AML_1""","""AML""","""AARSD1""","""OID21311""","""Q9BTE6""","""Oncology""",5.01745
1,"""AML_2""","""AML""","""AARSD1""","""OID21311""","""Q9BTE6""","""Oncology""",2.8679
2,"""AML_3""","""AML""","""AARSD1""","""OID21311""","""Q9BTE6""","""Oncology""",4.58825
3,"""AML_4""","""AML""","""AARSD1""","""OID21311""","""Q9BTE6""","""Oncology""",1.97255
4,"""AML_5""","""AML""","""AARSD1""","""OID21311""","""Q9BTE6""","""Oncology""",3.45995
...,...,...,...,...,...,...,...
2082004,"""PRC_157""","""PRC""","""ZBTB17""","""OID20082""","""Q13105""","""Cardiometabolic""",0.99695
2082005,"""PRC_159""","""PRC""","""ZBTB17""","""OID20082""","""Q13105""","""Cardiometabolic""",1.1206
2082006,"""PRC_160""","""PRC""","""ZBTB17""","""OID20082""","""Q13105""","""Cardiometabolic""",1.61685
2082007,"""PRC_161""","""PRC""","""ZBTB17""","""OID20082""","""Q13105""","""Cardiometabolic""",0.91665
2082008,"""PRC_163""","""PRC""","""ZBTB17""","""OID20082""","""Q13105""","""Cardiometabolic""",1.3003

In [5]:
#After this, just checking to make sure.....

# In order to check columns are succesfully placed
column_names = df.columns.tolist()
print("Column names:", column_names)

Column names: ['Sample_ID', 'Cancer', 'Assay', 'OlinkID', 'UniProt', 'Panel', 'NPX']

In [6]:
#compare the number of rows of txt file and converted csv, to make sure no data in dataset disappears
#number of rows of csv
file = open("pancancer.csv")
numline = len(file.readlines())
print (numline)

2082010

In [7]:
#number of rows of txt file

def count_rows(file_path):
    with open(file_path, 'r') as file:
        row_count = 0
        for line in file:
            row_count += 1
        return row_count

file_path = 'pancancer.txt'  # Replace 'your_file.txt' with the actual file path
rows = count_rows(file_path)
print(f"The file has {rows} rows.")

The file has 2082010 rows.

In [8]:
#compare first and last five rows of txt and csv files to make sure no data in dataset disappears
#first five rows of csv file 

df.head(5)

  Sample_ID Cancer     Assay     OlinkID   UniProt       Panel      NPX
0   "AML_1"  "AML"  "AARSD1"  "OID21311"  "Q9BTE6"  "Oncology"  5.01745
1   "AML_2"  "AML"  "AARSD1"  "OID21311"  "Q9BTE6"  "Oncology"   2.8679
2   "AML_3"  "AML"  "AARSD1"  "OID21311"  "Q9BTE6"  "Oncology"  4.58825
3   "AML_4"  "AML"  "AARSD1"  "OID21311"  "Q9BTE6"  "Oncology"  1.97255
4   "AML_5"  "AML"  "AARSD1"  "OID21311"  "Q9BTE6"  "Oncology"  3.45995

In [9]:
#first 5 rows of txt file

with open('pancancer.txt', 'r') as f:
    for i in range(5):  # Read the first 5 lines
        line = f.readline()
        print(line.strip())  # .strip() removes trailing newlines

"Sample_ID" "Cancer" "Assay" "OlinkID" "UniProt" "Panel" "NPX"
"AML_1" "AML" "AARSD1" "OID21311" "Q9BTE6" "Oncology" 5.01745
"AML_2" "AML" "AARSD1" "OID21311" "Q9BTE6" "Oncology" 2.8679
"AML_3" "AML" "AARSD1" "OID21311" "Q9BTE6" "Oncology" 4.58825
"AML_4" "AML" "AARSD1" "OID21311" "Q9BTE6" "Oncology" 1.97255

In [10]:
# Print the last 5 rows of csv file

df.tail(5)

,Sample_ID,Cancer,Assay,OlinkID,UniProt,Panel,NPX
2082004,"""PRC_157""","""PRC""","""ZBTB17""","""OID20082""","""Q13105""","""Cardiometabolic""",0.99695
2082005,"""PRC_159""","""PRC""","""ZBTB17""","""OID20082""","""Q13105""","""Cardiometabolic""",1.1206
2082006,"""PRC_160""","""PRC""","""ZBTB17""","""OID20082""","""Q13105""","""Cardiometabolic""",1.61685
2082007,"""PRC_161""","""PRC""","""ZBTB17""","""OID20082""","""Q13105""","""Cardiometabolic""",0.91665
2082008,"""PRC_163""","""PRC""","""ZBTB17""","""OID20082""","""Q13105""","""Cardiometabolic""",1.3003

In [11]:
## Print the last 5 rows of txt file

def read_last_n_lines(file_path, n):
    """Read the last n lines from a text file."""

    with open(file_path, 'r') as f:
        lines = f.readlines()
        return lines[-n:]

file_path = 'pancancer.txt'  # Replace with your file path
n = 5  # Number of lines to read from the end

last_lines = read_last_n_lines(file_path, n)

for line in last_lines:
    print(line, end='')  # The 'end' argument prevents extra newlines

"PRC_157" "PRC" "ZBTB17" "OID20082" "Q13105" "Cardiometabolic" 0.99695
"PRC_159" "PRC" "ZBTB17" "OID20082" "Q13105" "Cardiometabolic" 1.1206
"PRC_160" "PRC" "ZBTB17" "OID20082" "Q13105" "Cardiometabolic" 1.61685
"PRC_161" "PRC" "ZBTB17" "OID20082" "Q13105" "Cardiometabolic" 0.91665
"PRC_163" "PRC" "ZBTB17" "OID20082" "Q13105" "Cardiometabolic" 1.3003